---
- name: Updating operating system
  command: /usr/bin/yum update -y
  sudo: yes

- name: Installing Data Science Tools
  yum: pkg={{item}} state=installed
  with_items:
    - git 
    - python-devel 
    - python-virtualenvwrapper 
    - python-virtualenv 
    - python-pip 
    - Cython 
    - gcc 
    - gcc-c++ 
    - numpy 
    - python-pandas 
    - scipy 
    - PyYAML
    - graphviz-python 
    - graphviz
#    - python-psycopg2 
  sudo: yes

- name: Creating Virtual Environment
  command: /usr/bin/virtualenv --system-site-packages /home/{{unix_user}}/py2-env creates=/home/{{unix_user}}/py2-env

- name: Upgrading PIP
  command: /home/{{unix_user}}/py2-env/bin/pip install --upgrade pip

- name: Installing Jupyter in venv
  pip: name={{item}} virtualenv=/home/{{unix_user}}/py2-env state=present
  with_items:
    - seaborn
    - jupyter
    - sklearn
    - graphviz
    - statsmodels
    - patsy 

- name: Generating Jupyter config
  command: /home/{{unix_user}}/py2-env/bin/jupyter notebook --generate-config -y 

- name: Adding Jupyter configuration
  template: src=jupyter_notebook_config.py.j2 dest=/home/{{unix_user}}/.jupyter/jupyter_notebook_config.py owner={{unix_user}} group={{unix_user}} mode=0644

- name: Adding Matplotlib dir
  file: path=/home/{{unix_user}}/.config/matplotlib/ state=directory recurse=yes
  failed_when: False

- name: Adding Matplotlib config
  template: src=matplotlibrc.j2 dest=/home/{{unix_user}}/.config/matplotlib/matplotlibrc owner={{unix_user}} group={{unix_user}} mode=0644

- name: Adding starter script
  template: 
    src: run.py2.sh.j2 
    dest: "/home/{{unix_user}}/run.py2.sh" 
    owner: "{{unix_user}}" 
    group: "{{unix_user}}" 
    mode: "0750"

- name: Start Jupyter
  command: "nohup /home/{{unix_user}}/run.py2.sh"
  args:
    executable: "/bin/bash"


