---
- name: Check if tools are installed
  stat: path={{ item.path }}
  with_items:
    - {'name': mlocate,         'path': /usr/bin/updatedb}
    - {'name': vim,             'path': /usr/bin/vim}
    - {'name': screen,          'path': /usr/bin/screen}
    - {'name': net-tools,       'path': /usr/sbin/ifconfig}
    - {'name': bind-utils,      'path': /usr/bin/host}
    - {'name': ntp,             'path': /usr/sbin/ntpq}
    - {'name': epel-release,    'path': /dev/does-not-exists}
    - {'name': mc,              'path': /dev/does-not-exists}
    - {'name': yum-versionlock, 'path': /dev/does-not-exists}
  register: tools_installed
  sudo: yes

- name: Installing tools
  yum: name={{ item.item.name }} state=present
  with_items: "{{ tools_installed.results }}"
  when: item.stat.exists == false
  sudo: yes

- name: Rendering templates
  template: src={{ item.name }}.j2 dest={{ item.path }} owner=root group=root mode=0644
  with_items:
    - {'name': ntp.conf,    'path': /etc/ntp.conf}
    - {'name': limits.conf, 'path': /etc/security/limits.conf}
  sudo: yes

- name: Removing limits.d
  file: path=/etc/security/limits.d state=absent
  sudo: yes

- name: Make sure NTP is started up
  service: name=ntpd state=started enabled=yes
  sudo: yes

- name: Disables ipv6
  sysctl: name={{ item.name }} value={{ item.value }} state=present sysctl_set=yes reload=yes
  sudo: yes
  with_items:
    - {'name': net.ipv6.conf.all.disable_ipv6,        'value': 1}
    - {'name': net.ipv6.conf.default.disable_ipv6,    'value': 1}

- name: Ensure the firewall is disabled
  sudo: yes
  service: name=firewalld state=stopped enabled=no
  ignore_errors: yes

- name: NSA hack disabled
  selinux: state=disabled
  sudo: yes
  changed_when: False

- name: Rendering sysctl
  sysctl: name={{ item.name }} value={{ item.value }} state=present
  with_items:
    - {'name': vm.swappiness,                 'value': 5}
    - {'name': net.core.rmem_max,             'value': 16777216}
    - {'name': net.core.wmem_max,             'value': 16777216}
    - {'name': net.ipv4.tcp_rmem,             'value': '4096 87380 16777216'}
    - {'name': net.ipv4.tcp_wmem,             'value': '4096 87380 16777216'}
    - {'name': net.ipv4.tcp_tw_reuse,         'value': 1}
    - {'name': net.ipv4.tcp_tw_recycle,       'value': 1}
    - {'name': net.ipv4.tcp_fin_timeout,      'value': 30}
    - {'name': net.ipv4.tcp_syncookies,       'value': 1}
    - {'name': net.ipv4.tcp_max_syn_backlog,  'value': 65536}
  sudo: yes
